driver:
  name: qemu

platforms:
  - name: x86_64
    driver:
      image_path: ./images
      image: disk.img
      username: ubuntu
      password: ubuntu
      hostshares:
        - path: shared
          mountpoint: /mnt/shared

  - name: arm64
    driver:
      image_path: ./images
      bios: ./images/arm-bios.fd
      image: disk.img
      binary: ./qemu-hacked-arm
      username: ubuntu
      password: ubuntu
      hostshares:
        - path: shared
          mountpoint: /mnt/shared

suites:
  - name: vm
