driver:
  name: qemu

platforms:
  - name: amd64
    driver:
      image_path: ./images
      image: disk.img
      username: ubuntu
      password: ubuntu
      hostshares:
        - path: shared
          mountpoint: /mnt/shared

suites:
  - name: vm
