#!/usr/bin/env python3

import sys
import os
import re

params = ' '.join(sys.argv[1:])

hacked_argv = ('/usr/bin/qemu-system-aarch64 -M virt ' + hacked_params).split()
os.execv(hacked_argv[0], hacked_argv)
