#!/usr/bin/env python3

import sys
import os
import re

params = ' '.join(sys.argv[1:])

hacked_params = re.sub(
    (r'-device virtio-scsi-pci,id=scsi '
     r'-device scsi-hd,drive=drive0 '
     r'-drive if=none,id=drive0,snapshot=on,file=(\S+) '),
    (r'-device virtio-blk-device,drive=image '
     r'-drive if=none,id=image,snapshot=on,file=\1 '),
    params,
)

hacked_argv = ('/usr/bin/qemu-system-aarch64 -M virt ' + hacked_params).split()
os.execv(hacked_argv[0], hacked_argv)
