#!/usr/bin/env python3

import shutil
from subprocess import check_call
import yaml

BUILD_CONFIG_FILE = 'build_config.yml'
LIQUID_SETUP_REPO = "https://github.com/liquidinvestigations/setup.git"
LIQUID_SETUP_TARGET = 'shared/setup'

# TODO use pathlib.Path

def main():
    # get configuration
    with open(BUILD_CONFIG_FILE, 'r') as f:
        build_config = yaml.load(f)

    # clone setup
    check_call(['git', 'clone', LIQUID_SETUP_REPO, LIQUID_SETUP_TARGET])

    # checkout requested branch
    check_call(['git', 'checkout', build_config['git_repo_versions']['setup']], cwd=LIQUID_SETUP_TARGET)

    # move config to target
    shutil.copy(BUILD_CONFIG_FILE, LIQUID_SETUP_TARGET + "/ansible/vars/config.yml")

if __name__ == "__main__":
    main()
